### ISSUE TITLE
Investigate alternate JUnit test representation

### ISSUE THREAD

**Issue by kittylyst** [RedHatInsights/insights-runtimes-inventory#118]
Would this work for us?

https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter

**Comment by aptmac** [comment]
Took a quick look into this, see changes: https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:tree-reporter?expand=1

There is a default setting that disables console reporting during test runs, which might not make much sense for debugging the integration tests, but will keep the unit tests tidy.

I can open a PR if these look like what you were hoping.

## Unit tests:
Here I kept the default setting of turning off all console reporting, but then used the suggested configuration to print stacktraces, stderr, and stdout in the event of a test failure or error.

When everything passes:
![unit-tests-okay](https://github.com/RedHatInsights/insights-runtimes-inventory/assets/10425301/f6fa8933-bb39-4532-88d9-3ca05b3e6c6f)

When there's a failure:
![unit-tests-failure](https://github.com/RedHatInsights/insights-runtimes-inventory/assets/10425301/be7ab219-073a-4ebd-8fab-0904fcd64ceb)

## Integration tests:
The default config turns off all console reporting, but because these tests work with TestContainers, Quarkus, and the database it is probably more helpful to keep those logs visible because we might not get the whole picture of an error from just a stacktrace of an assertion error. The tree reporter is still nice in this case because the green is a nice visual indicator of what the logs are referring to.

![integration-tests](https://github.com/RedHatInsights/insights-runtimes-inventory/assets/10425301/c1a033fa-1314-4c21-a2b0-9dc041100524)

**Comment by kittylyst** [comment]
Sorry, missed your comment here @aptmac - yes, please proceed to make a PR for this.

This issue has now migrated to https://issues.redhat.com/browse/MWTELE-102 - please followup there.
