### ISSUE TITLE
Make REST service return all available data

### ISSUE THREAD

**Issue by kittylyst** [RedHatInsights/insights-runtimes-inventory#48]

**Comment by kittylyst** [comment]
* Jar hashes
* EAP-specific data

**Comment by aptmac** [comment]
I've been working away on some endpoints, the eap instance data isn't ready yet so I'll get to that afterwards. In the meantime, I adjusted the current `/instance` endpoint, and added some more. I have a wip branch that I'm hacking away at, the comparison against upstream/main can be seen here: [link](https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:add-rest-endpoints?expand=1) [0]

I thought it'd be nice to be able to fetch a list of ids for each the jvm instances and jar hashes, as well as being able to retrieve all or a single instance/hash. If these are incorrect or need adjusting let me know and I can restructure them.

`/instance`: this one currently fetches all the instances and then returns index 0. Adjusted to given a jvm instance id, fetch the relevant instance. 
`/instance-ids`: given a hostname and group id, fetch the relevant instance ids for the host
`/instances`: given a hostname, fetch all jvm instances for the host

`/jarhash-ids`: given a jvm instance id, fetch the jarhash ids associated with it
`/jarhash`: given a jarhash id, fetch the associated jar hash
`/jarhashes`: given a jvm instance id, fetch all jar hashes for it

A couple other notes:
- The db complains that there isn't a eap_instance relation, so I added a create table command into the existing sql script
- The jarhash table has a fk on the jvm instance id (uuid), however the jarhash java class stores the entire jvm instance. So it can look something like this, where the `instance=JvmInstance[..]` lists out the entire contents of the parent instance:
```
{
  id=5171a2af-b782-49f6-a59b-88f7f957d6fc,
  instance=JvmInstance{[..]},
  name='jboss-modules.jar',
  groupId='org.jboss.modules',
  vendor='JBoss by Red Hat',
  version='1.12.0.Final-redhat-00001', 
  sha1Checksum='82a8c99551533f4448675f273665cb6d7b750511',
  sha256Checksum='d808a03cf5f844f0d1cf52b340a5c4ad836c052e1288a9b5ac8ca6df6ae9e000',
  sha512Checksum='4c85d6f74cb8a34dca6748873f9b38457c04f253c4b7d1e088010d13eec7021145b338979adf8991f54c2b6241da7d350c2cfac849e603c286aa5fb13edf560f'
}
```
- Because of the above, I added `@JsonBackReference` and `@JsonManagedReference` to the JarHash and JvmInstance classes respectively, because retrieving information from the db could cause an infinite recursion error. The Jar Hash contains the entire JvmInstance, which in turn contains a set of Jar Hashes including this current one, which contains the entire JvmInstance ..etc.
  
Will clean this up and separate the hacky testing unit test into individual tests next week. Can also add a unit test for https://github.com/RedHatInsights/insights-runtimes-inventory/pull/72 as mentioned in the review comments.

[0] https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:add-rest-endpoints?expand=1

**Comment by aptmac** [comment]
Opened PR for jvm instance and jar hash endpoints here: https://github.com/RedHatInsights/insights-runtimes-inventory/pull/78

I'll give a deeper look into the eap instance data retrieval once I've gotten some feedback on the PR to make sure I'm on the right track here. At a quick glance I'm having some difficulties using the unit tests to pull eap instance data out of the database, so I'd rather not have to rebase and debug a massive pull-request and will opt to split this issue up into two parts instead.

**Comment by kittylyst** [comment]
PR #78 has been merged and deployed, but it is incorrect.

Hitting the REST endpoint causes errors like these:
`2023-09-11 09:43:47,234 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/runtimes-inventory-service/v1/instance/?hostname=uriel.local failed, error id: f3b685ff-7283-44d7-92c7-bcd55a74ea5f-1: java.lang.NullPointerException: Cannot invoke "String.length()" because "name" is null
at java.base/java.util.UUID.fromString(UUID.java:237)
at com.redhat.runtimes.inventory.web.DisplayInventory.getJvmInstanceRecord(DisplayInventory.java:118)
at com.redhat.runtimes.inventory.web.DisplayInventory$quarkusrestinvoker$getJvmInstanceRecord_42179836f2505dd965a0c948378eae515a23f8f0.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)`

@aptmac Please fix, starting with a (failing) test that provokes this issue so that once fixed, this can't come back.

**Comment by aptmac** [comment]
I have some basic EapInstance endpoints up and running at the moment, mainly to mimic the JvmInstance ones so we have:

- `/eap-instances/`
- `/eap-instance-ids/`
- `/eap-instance/`

I'm guessing the aim of returning all the data would be just to have an endpoint we can test against and verify that all the information is in a format/place where we want it? Practically the Eap Instance data is very large, and these endpoints wouldn't be useful unless heavily modified or re-imagined.

I ran a few tests to illustrate the size:

```
| Size (bytes) | What was removed               |
| ------------ | ------------------------------ |
| 5044483      | raw eap_example1.json file     |
| 18056234     | Nothing (returned EapInstance) |
| 12669674     | raw                            |
| 12669674     | deployments                    |
| 12669674     | configuration                  |
| 12669664     | jars                           |
| 10921356     | modules                        |
| 5534788      | jvm packages                   |
| 5534400      | jvm command                    |
| 147836       | jvm args                       |
```

Here I persisted the file `eap_example1.json` (~4.9mb) to the db, and then retrieved the resulting EapInstance and piped it into a json file. Each iteration I removed an attribute from EapInstance to see the impact on size.

The raw EapInstance returned from the db is ~18mb, removing the raw json dropped it down to ~13mb, and then further removing the java packages brought it down to ~5.3mb. Removing the jvm args brings this down to 145kb.

Is this type of endpoint still useful in any way? As an aside, I took a look at the mockups and have written a couple endpoints that serve just the information to populate a two pages worth, it may be more practical to finalize the ui and design the endpoints around them.

**Comment by aptmac** [comment]
Branch: https://github.com/aptmac/insights-runtimes-inventory/tree/eapinstance
Comparison: https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:eapinstance

I finished writing some basic tests for the eap instance endpoints as they currently are, and have posted a link to my branch and the comparison between that branch and main.

There are a couple things of note:
- the `eap_instance_jar_hash` table is indeed necessary for the retrieval of eap instance data, hibernate complains about a missing relation otherwise ([link](https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:eapinstance#diff-1b453f67e895aa72f5b2c43a3e4e7ae2e138247deb2f0ca086cf56b2e5290033R155))
- `@Lob` does not work with hibernate in auto-commit mode, so the annotations had to be removed on the large raw strings in EapInstance and EapConfiguration. I tried setting it to false in the `application.properties` for the rest component by using the `quarkus.hibernate-orm.unsupported-properties`, but that didn't have any effect. ([link](https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:eapinstance#diff-685d0e3486f1882b1ffa55e4bf6b4f00655e5d916feea2a39734ea98a437cb10L155))
- I had to add some `@JsonManagedReference` and `@JsonBackReference` between EapInstance and both EapDeployments and EapConfiguration, otherwise there's infinite recursion when retrieving info ([link](https://github.com/RedHatInsights/insights-runtimes-inventory/compare/main...aptmac:insights-runtimes-inventory:eapinstance#diff-685d0e3486f1882b1ffa55e4bf6b4f00655e5d916feea2a39734ea98a437cb10R40))
- in the tests, I tried using `eap-connect1.json` and `eap-connect2.json` to populate the db with, but they have a different format from eap_example1.json (which looks to be our point of truth at the moment). Are the first two jsons valid eap instances?

**Comment by aslicerh** [comment]
@aptmac Just for an update, I'm removing `@Lob` annotations officially. Turns out they don't play well with Postgres. If we end up with performance issues from the large fields we'll separate them out to object tables manually and lazy load them through hibernate.

**Comment by aptmac** [comment]
Eap data endpoints were added as of: https://github.com/RedHatInsights/insights-runtimes-inventory/pull/97

Along with the previous commit for JarHashes, it looks like the criteria for this issue has been met, closing this issue.
